site: https://editor.csdn.net/md/

# 文章标签（md中没有设置标签的时候上传这个）
tags:
  - 自动化上传

# 分类专栏（md中没有设置专栏的时候上传这个）
categories:
  - 程序那些事

# 分类专栏映射，左侧为md中的名称（如果是多级分类使用,分隔），右侧为csdn的专栏名称
categories_tables:
  "编程学习,Python": "速通Python"
  "编程学习,C语言": "初始C语言"
  "编程学习,Cpp": "遇见C++"
  "编程学习,Docker学习": "Docker & Nas"
  "编程学习,Linux": "玩上Linux"
  "编程学习,Redis": "MySQL"
  "编程学习,把题目都给刷干净": "把题目都给刷干净"
  "编程学习,数据库SQL": "MySQL"
  "编程学习,数据结构": "数据结构太复杂"
  "编程学习,没事就吃树莓派": "没事就吃树莓派"
  "编程学习,计算机网络": "计组和计网"
  "编程学习,项目开发记录": "SLAM"
  "差生文具多,Docker真好玩": "Docker & Nas"
  "差生文具多,图床": "差生文具多"
  "差生文具多,博客建站": "差生文具多"
  "差生文具多,电脑使用小贴士": "差生文具多"
  "差生文具多,笔记软件": "差生文具多"
  "差生文具多,编程工具": "差生文具多"


# 可见范围 全部可见, 仅我可见,粉丝可见,VIP可见
visibility: 全部可见


